### ISSUE TITLE
Free Members are not added to campaign

### ISSUE THREAD

**Issue by rlwmmw** [strangerstudios/pmpro-getresponse#1] opened 2014-04-02 02:53 UTC
Members registering for a free ($0.00) membership are not added to the campaign.  This is true with or without reCaptcha.

Members are only added to campaigns that require payment.
## 

Rusty

**Comment by andrewlimaza** [comment] 2018-07-31 13:26
This is working as intended as of latest test. Closing this old thread.

Please feel free to open a thread if this still exists.

**Closed by andrewlimaza** 2018-07-31 13:26 UTC
